# Generated by Django 6.0.2 on 2026-08-27 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_alter_lugar_latitud_alter_lugar_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.AddField(
            model_name='lugar',
            name='compartidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lugar',
            name='horario',
            field=models.CharField(blank=True, default='08:00 AM - 06:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='lugar',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lugar',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lugares', to='turismo.categoria'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='latitud',
            field=models.FloatField(default=-12.483, help_text='Latitud decimal'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='longitud',
            field=models.FloatField(default=-76.796, help_text='Longitud decimal'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilusuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('organizador', models.CharField(default='Municipalidad Distrital de Pucusana', max_length=150)),
                ('estado', models.CharField(choices=[('publicado', 'Publicado'), ('pendiente', 'Pendiente')], default='publicado', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='turismo.categoria')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
